### ISSUE TITLE
Some images uploaded are upside down or sideways in cropper

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#323]
This might be due to orientation saved in the image's meta data. Is there a way to check or set orientation?

**Comment by giovanniorigins** [comment]
I was checking the docs and repo, and found this: 
http://stackoverflow.com/questions/36034437/jcrop-incorrect-orientation-from-iphone-upload-how-i-can-do

1. user selects and uploads photo to server as-is
2. when the upload submits, I create a copy of the image which is physically rotated to the orientation indicated in the exif data, and ensure that the exif data is updated accordingly. (e.g. if exif originally indicated 90 deg CW rotation, I do that rotation, and update the exif so that it no longer indicates this rotation)
3. when the page reloads after submission, I show the jCrop workspace with the new version of the image.


If this doesn't or can't work, I'll need to do some testing with my phone.

**Comment by nkeena** [comment]
Hmm .. this is looking pretty involved. I'm not sure we want to invest that kind of time before launch. 

I think we issue an enhancement for this and ship at a later release.

Maybe do some testing to see if users can correct the orientation on their computer first, before uploading. Our reps could instruct users in that way if they are having issues.

Thoughts?

**Comment by giovanniorigins** [comment]
I agree with that, sounds good.
